### ISSUE TITLE
Bitcoin Testnet addresses not supported

### ISSUE THREAD

**Issue by yivo** [vtm9/adequate_crypto_address#3]
```ruby
AdequateCryptoAddress.valid?('mv4rnyY3Su5gjcDNzbMLKBQkBicCtHUtFB', :btc) # false
```

**Comment by vtm9** [comment]
Strange, can you write some details of how you made this address? Thx

**Comment by yivo** [comment]
@vtm9 You can get this address from bitcoind when it runs with testnet=1 (test BTC network for development purposes).

**Comment by vtm9** [comment]
try 0.1.5 version

**Comment by vtm9** [comment]
@yivo Yo, does it works in your case?

**Comment by yivo** [comment]
Thanks, @vtm9. It works now.
