### ISSUE TITLE
AdequateCryptoAddress::UnknownCurrency: Wrong currency btc

### ISSUE THREAD

**Issue by doug420** [vtm9/adequate_crypto_address#5]
AdequateCryptoAddress.valid?('12QeMLzSrB8XH8FvEzPMVoRxVAzTr5XM2y', 'BTC')
Any response on that? why i am facing this issue while having testing btc testnet!
 errors.add(:address, 'invalid address') unless AdequateCryptoAddress.valid?(address, currency)

**Comment by vtm9** [comment]
Sorry, it works fine for me
```
➜  adequate_crypto_address git:(master)  bin/console
[1] pry(main)> AdequateCryptoAddress.valid?('12QeMLzSrB8XH8FvEzPMVoRxVAzTr5XM2y', 'BTC')
=> true
```
