### ISSUE TITLE
Code gap between this repo and rubygems?

### ISSUE THREAD

**Issue by vikkanaev** [vtm9/adequate_crypto_address#8]
Today I tried to run this gem on ruby 3 and it's doesn't install
```
#Gemfile
gem 'adequate_crypto_address'

sh > bundle install
...
adequate_crypto_address (~> 0.1.5) was resolved to 0.1.5, which depends on
      digest-sha3 (~> 1.1.0) was resolved to 1.1.0, which depends on
        Ruby (~> 2.2)
```
I looked to [gemspec](https://github.com/vtm9/adequate_crypto_address/blob/master/adequate_crypto_address.gemspec#L22) and there is no digest-sha3 dependency
But digest-sha3 dependency exists on [rubygems](https://rubygems.org/gems/adequate_crypto_address)

As I can see version 0.1.5 released to rubygems on May 13, 2019
But on 1 Dec 2021 @q9f switch gem from digest-sha3 to keccak ([commit](https://github.com/vtm9/adequate_crypto_address/commit/408c534429eba58b3dbba52440ea667a4e11ff18))

Could you be so kind to download this changes on rubygems?

**Comment by vtm9** [comment]
sure, sorry for late.
